[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.61.0",
    "streamlit-calendar>=1.2.1",
    "streamlit>=1.42.0",
    "markdown>=3.7",
]
